package com.cs.SchoolSystem.po;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.userID
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.userName
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.sex
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.birthYear
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    private Date birthyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.grade
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    private Date grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.collegeID
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    private Integer collegeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.userID
     *
     * @return the value of student.userID
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.userID
     *
     * @param userid the value for student.userID
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.userName
     *
     * @return the value of student.userName
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.userName
     *
     * @param username the value for student.userName
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.sex
     *
     * @return the value of student.sex
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.sex
     *
     * @param sex the value for student.sex
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.birthYear
     *
     * @return the value of student.birthYear
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    public Date getBirthyear() {
        return birthyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.birthYear
     *
     * @param birthyear the value for student.birthYear
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    public void setBirthyear(Date birthyear) {
        this.birthyear = birthyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.grade
     *
     * @return the value of student.grade
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    public Date getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.grade
     *
     * @param grade the value for student.grade
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    public void setGrade(Date grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.collegeID
     *
     * @return the value of student.collegeID
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    public Integer getCollegeid() {
        return collegeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.collegeID
     *
     * @param collegeid the value for student.collegeID
     *
     * @mbg.generated Thu Apr 12 16:46:25 CST 2018
     */
    public void setCollegeid(Integer collegeid) {
        this.collegeid = collegeid;
    }
}