package com.cs.SchoolSystem.mapper;

import com.cs.SchoolSystem.po.Selectedcourse;
import com.cs.SchoolSystem.po.SelectedcourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SelectedcourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Thu Apr 12 16:45:40 CST 2018
     */
    long countByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Thu Apr 12 16:45:40 CST 2018
     */
    int deleteByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Thu Apr 12 16:45:40 CST 2018
     */
    int insert(Selectedcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Thu Apr 12 16:45:40 CST 2018
     */
    int insertSelective(Selectedcourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Thu Apr 12 16:45:40 CST 2018
     */
    List<Selectedcourse> selectByExample(SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Thu Apr 12 16:45:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") Selectedcourse record, @Param("example") SelectedcourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table selectedcourse
     *
     * @mbg.generated Thu Apr 12 16:45:40 CST 2018
     */
    int updateByExample(@Param("record") Selectedcourse record, @Param("example") SelectedcourseExample example);
}